image: ubuntu:16.04

before_script:
  - apt-get install curl -y
  - curl https://install.meteor.com/ | sh
  - apt-get install node npm meteor -y


publish_live:
  only:
    - master
  script:
    - meteor build --directory meteor-app
    - cd meteor-app/bundle/
    - pushd programs/server/
    - npm install
    - popd
    - lftp -u $FTP_USER,$FTP_PASS -e 'mirror --only-newer --reverse --verbose --no-symlinks ./ ./' $FTP_HOST
  tags:
    - docker