image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install curl git software-properties-common -y
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt-get install -y nodejs
  - curl https://install.meteor.com/ | sh
  - apt-add-repository ppa:cordova-ubuntu/ppa
  - apt-get update
  - apt-get install cordova-cli -y


publish_live:
  only:
    - master
  script:
    - npm install
    - meteor build --directory ./ --allow-superuser --server http://158.197.204.103:8000/
    - cd meteor-app/bundle/
    - pushd programs/server/
    - npm install
    - popd
    - lftp -u $FTP_USER,$FTP_PASS -e 'mirror --only-newer --reverse --verbose --no-symlinks ./ ./' $FTP_HOST
  tags:
    - docker