image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install curl -y
  - curl https://install.meteor.com/ | sh


publish_live:
  only:
    - master
  script:
    - meteor build --directory ./ --allow-superuser --server http://158.197.204.103:8000/
    - cd meteor-app/bundle/
    - pushd programs/server/
    - npm install
    - popd
    - lftp -u $FTP_USER,$FTP_PASS -e 'mirror --only-newer --reverse --verbose --no-symlinks ./ ./' $FTP_HOST
  tags:
    - docker