image: ubuntu:16.04


variables:
  LANG: en_US.UTF-8
  ANDROID_COMPONENTS: platform-tools,android-23,build-tools-23.0.2,build-tools-24.0.0
  ANDROID_HOME: /usr/local/android-sdk
  ANDROID_SDK_HOME: $ANDROID_HOME
  ANDROID_NDK_HOME: /usr/local/android-ndk
  JENKINS_HOME: $HOME


# Export JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/

# Support Gradle
ENV TERM dumb
ENV JAVA_OPTS "-Xms4096m -Xmx4096m"
ENV GRADLE_OPTS "-XX:+UseG1GC -XX:MaxGCPauseMillis=1000"

before_script:
  - locale-gen $LANG
  - apt-get update
  - apt-get install curl git software-properties-common -y
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt-get install -y nodejs
  - curl https://install.meteor.com/ | sh
  - apt-add-repository ppa:cordova-ubuntu/ppa
  - apt-get update
  - apt-get install cordova-cli -y
  - apt-get install -y autoconf build-essential bzip2 curl gcc git groff lib32stdc++6 lib32z1 lib32z1-dev lib32ncurses5 lib32bz2-1.0 libc6-dev libgmp-dev libmpc-dev libmpfr-dev libxslt-dev libxml2-dev m4 make ncurses-dev ocaml openssh-client pkg-config python-software-properties rsync software-properties-common unzip wget zip zlib1g-dev --no-install-recommends
  - apt-add-repository ppa:openjdk-r/ppa
  - apt-get update
  - apt-get -y install openjdk-8-jdk
  - rm -rf /var/lib/apt/lists/*
  - apt-get clean
  - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar -xvzf android-sdk_r24.4.1-linux.tgz
  - mv android-sdk-linux /usr/local/android-sdk
  - rm android-sdk_r24.4.1-linux.tgz
  - echo y | /usr/local/android-sdk/tools/android update sdk --filter "${ANDROID_COMPONENTS}" --no-ui -a
  - wget http://dl.google.com/android/repository/android-ndk-r12-linux-x86_64.zip
  - unzip android-ndk-r12-linux-x86_64.zip
  - mv android-ndk-r12 /usr/local/android-ndk
  - rm android-ndk-r12-linux-x86_64.zip



publish_live:
  only:
    - master
  script:
    - npm install
    - meteor build --directory ./ --allow-superuser --server http://158.197.204.103:8000/
    - cd meteor-app/bundle/
    - pushd programs/server/
    - npm install
    - popd
    - lftp -u $FTP_USER,$FTP_PASS -e 'mirror --only-newer --reverse --verbose --no-symlinks ./ ./' $FTP_HOST
  tags:
    - docker